project:
  type: website

  render:
    - "*.qmd"

  resources: 
    - "files/**"

freeze: auto

website:
  title: "FTW"
  favicon: "files/favicon-ftw.png"
  site-url: "https://fruitatechwizard.com"
  navbar:
    pinned: false
    # logo: "files/favicon-bike.png"
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: "Services"
      - href: contact.qmd
        text: "Contact"
      - href: about.qmd
        text: "About"
      - href: https://www.westword.com/opinion/wtf-fruita-controversial-slogan-wears-out-its-welcome-5826454/
        text: "WTF?"
        target: _blank

  page-footer:
    left: |
      <span class="faux-block">Â© 2025 Fruita Tech Wizard </span>
    right: | 
      {{< fa phone >}} [(720) 213-6374](tel:+17202136374) {{< fa envelope >}} [help@fruitatechwizard.com](mailto:help@fruitatechwizard.com)


format:
  html:
    theme: 
      - lux
      - html/styles.scss
#    grid: 
#      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
#    highlight-style: monokai

  
  
  
